/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.gnet.uc.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum CaseMessageId implements org.apache.thrift.TEnum {
  WB_CASE_PUBLISH(1),
  WB_CASE_COMMENT(2),
  WB_CASE_FORWARD(3),
  WB_CASE_PRAISE(4);

  private final int value;

  private CaseMessageId(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CaseMessageId findByValue(int value) { 
    switch (value) {
      case 1:
        return WB_CASE_PUBLISH;
      case 2:
        return WB_CASE_COMMENT;
      case 3:
        return WB_CASE_FORWARD;
      case 4:
        return WB_CASE_PRAISE;
      default:
        return null;
    }
  }
}
