/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.gnet.uc.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ChatMediaType implements org.apache.thrift.TEnum {
  MediaTypeAudio(1),
  MediaTypeImage(2),
  MediaTypeVideo(3),
  MediaTypeEmotion(4),
  MediaTypeMeetingRecord(5);

  private final int value;

  private ChatMediaType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ChatMediaType findByValue(int value) { 
    switch (value) {
      case 1:
        return MediaTypeAudio;
      case 2:
        return MediaTypeImage;
      case 3:
        return MediaTypeVideo;
      case 4:
        return MediaTypeEmotion;
      case 5:
        return MediaTypeMeetingRecord;
      default:
        return null;
    }
  }
}
