/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.gnet.uc.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ConfAlertMessageId implements org.apache.thrift.TEnum {
  FifteenMinutesAlert(1),
  ZeroMinutesAlert(2),
  ConfStartAlert(3),
  ConfEndAlert(4),
  PartJoinAlert(5),
  PartQuitAlert(6);

  private final int value;

  private ConfAlertMessageId(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ConfAlertMessageId findByValue(int value) { 
    switch (value) {
      case 1:
        return FifteenMinutesAlert;
      case 2:
        return ZeroMinutesAlert;
      case 3:
        return ConfStartAlert;
      case 4:
        return ConfEndAlert;
      case 5:
        return PartJoinAlert;
      case 6:
        return PartQuitAlert;
      default:
        return null;
    }
  }
}
