/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.gnet.uc.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ContentType implements org.apache.thrift.TEnum {
  thrift_type(1),
  mime_type(2);

  private final int value;

  private ContentType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ContentType findByValue(int value) { 
    switch (value) {
      case 1:
        return thrift_type;
      case 2:
        return mime_type;
      default:
        return null;
    }
  }
}
