/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.gnet.uc.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum DeviceType implements org.apache.thrift.TEnum {
  Iphone(1),
  Android(2),
  PC(3),
  Background(4),
  Ipad(5),
  Web(6);

  private final int value;

  private DeviceType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static DeviceType findByValue(int value) { 
    switch (value) {
      case 1:
        return Iphone;
      case 2:
        return Android;
      case 3:
        return PC;
      case 4:
        return Background;
      case 5:
        return Ipad;
      case 6:
        return Web;
      default:
        return null;
    }
  }
}
