/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.gnet.uc.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum GroupMessageId implements org.apache.thrift.TEnum {
  TextContent(1),
  MediaContent(2),
  DisMemberAdd(3),
  DisMemberDel(4),
  DisNameUpdate(5),
  DiscussionCreate(6),
  DiscussionTop(7),
  SummaryCreate(8),
  DocumentForward(9),
  AlertRuleUpdate(10),
  DiscussionClose(11),
  MsgNotifyUpdate(12),
  DisMemberKick(13),
  DocumentDel(14),
  CodeCreate(15),
  CodeForward(16),
  CodeDel(17),
  CommentCreate(18),
  CommentDel(19),
  DisAvatarUpdate(20),
  DisStateUpdate(21),
  CloudFileCreate(22),
  MemberRoleUpdate(27),
  ReportContent(28),
  RevocationMsg(29),
  DiscussionScope(30);

  private final int value;

  private GroupMessageId(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static GroupMessageId findByValue(int value) { 
    switch (value) {
      case 1:
        return TextContent;
      case 2:
        return MediaContent;
      case 3:
        return DisMemberAdd;
      case 4:
        return DisMemberDel;
      case 5:
        return DisNameUpdate;
      case 6:
        return DiscussionCreate;
      case 7:
        return DiscussionTop;
      case 8:
        return SummaryCreate;
      case 9:
        return DocumentForward;
      case 10:
        return AlertRuleUpdate;
      case 11:
        return DiscussionClose;
      case 12:
        return MsgNotifyUpdate;
      case 13:
        return DisMemberKick;
      case 14:
        return DocumentDel;
      case 15:
        return CodeCreate;
      case 16:
        return CodeForward;
      case 17:
        return CodeDel;
      case 18:
        return CommentCreate;
      case 19:
        return CommentDel;
      case 20:
        return DisAvatarUpdate;
      case 21:
        return DisStateUpdate;
      case 22:
        return CloudFileCreate;
      case 27:
        return MemberRoleUpdate;
      case 28:
        return ReportContent;
      case 29:
        return RevocationMsg;
      case 30:
        return DiscussionScope;
      default:
        return null;
    }
  }
}
