/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.gnet.uc.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2016-8-12")
public class InstantIQInviteContent implements org.apache.thrift.TBase<InstantIQInviteContent, InstantIQInviteContent._Fields>, java.io.Serializable, Cloneable, Comparable<InstantIQInviteContent> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("InstantIQInviteContent");

  private static final org.apache.thrift.protocol.TField CONF_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("confId", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField HOST_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("hostId", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField CONF_PWD_FIELD_DESC = new org.apache.thrift.protocol.TField("confPwd", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField IS_RESERVE_FIELD_DESC = new org.apache.thrift.protocol.TField("isReserve", org.apache.thrift.protocol.TType.BYTE, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new InstantIQInviteContentStandardSchemeFactory());
    schemes.put(TupleScheme.class, new InstantIQInviteContentTupleSchemeFactory());
  }

  public int confId; // required
  public int hostId; // required
  public String confPwd; // required
  public byte isReserve; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CONF_ID((short)1, "confId"),
    HOST_ID((short)2, "hostId"),
    CONF_PWD((short)3, "confPwd"),
    IS_RESERVE((short)4, "isReserve");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CONF_ID
          return CONF_ID;
        case 2: // HOST_ID
          return HOST_ID;
        case 3: // CONF_PWD
          return CONF_PWD;
        case 4: // IS_RESERVE
          return IS_RESERVE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __CONFID_ISSET_ID = 0;
  private static final int __HOSTID_ISSET_ID = 1;
  private static final int __ISRESERVE_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.IS_RESERVE};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CONF_ID, new org.apache.thrift.meta_data.FieldMetaData("confId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.HOST_ID, new org.apache.thrift.meta_data.FieldMetaData("hostId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.CONF_PWD, new org.apache.thrift.meta_data.FieldMetaData("confPwd", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.IS_RESERVE, new org.apache.thrift.meta_data.FieldMetaData("isReserve", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BYTE)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(InstantIQInviteContent.class, metaDataMap);
  }

  public InstantIQInviteContent() {
  }

  public InstantIQInviteContent(
    int confId,
    int hostId,
    String confPwd)
  {
    this();
    this.confId = confId;
    setConfIdIsSet(true);
    this.hostId = hostId;
    setHostIdIsSet(true);
    this.confPwd = confPwd;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public InstantIQInviteContent(InstantIQInviteContent other) {
    __isset_bitfield = other.__isset_bitfield;
    this.confId = other.confId;
    this.hostId = other.hostId;
    if (other.isSetConfPwd()) {
      this.confPwd = other.confPwd;
    }
    this.isReserve = other.isReserve;
  }

  public InstantIQInviteContent deepCopy() {
    return new InstantIQInviteContent(this);
  }

  @Override
  public void clear() {
    setConfIdIsSet(false);
    this.confId = 0;
    setHostIdIsSet(false);
    this.hostId = 0;
    this.confPwd = null;
    setIsReserveIsSet(false);
    this.isReserve = 0;
  }

  public int getConfId() {
    return this.confId;
  }

  public InstantIQInviteContent setConfId(int confId) {
    this.confId = confId;
    setConfIdIsSet(true);
    return this;
  }

  public void unsetConfId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CONFID_ISSET_ID);
  }

  /** Returns true if field confId is set (has been assigned a value) and false otherwise */
  public boolean isSetConfId() {
    return EncodingUtils.testBit(__isset_bitfield, __CONFID_ISSET_ID);
  }

  public void setConfIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CONFID_ISSET_ID, value);
  }

  public int getHostId() {
    return this.hostId;
  }

  public InstantIQInviteContent setHostId(int hostId) {
    this.hostId = hostId;
    setHostIdIsSet(true);
    return this;
  }

  public void unsetHostId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __HOSTID_ISSET_ID);
  }

  /** Returns true if field hostId is set (has been assigned a value) and false otherwise */
  public boolean isSetHostId() {
    return EncodingUtils.testBit(__isset_bitfield, __HOSTID_ISSET_ID);
  }

  public void setHostIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __HOSTID_ISSET_ID, value);
  }

  public String getConfPwd() {
    return this.confPwd;
  }

  public InstantIQInviteContent setConfPwd(String confPwd) {
    this.confPwd = confPwd;
    return this;
  }

  public void unsetConfPwd() {
    this.confPwd = null;
  }

  /** Returns true if field confPwd is set (has been assigned a value) and false otherwise */
  public boolean isSetConfPwd() {
    return this.confPwd != null;
  }

  public void setConfPwdIsSet(boolean value) {
    if (!value) {
      this.confPwd = null;
    }
  }

  public byte getIsReserve() {
    return this.isReserve;
  }

  public InstantIQInviteContent setIsReserve(byte isReserve) {
    this.isReserve = isReserve;
    setIsReserveIsSet(true);
    return this;
  }

  public void unsetIsReserve() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ISRESERVE_ISSET_ID);
  }

  /** Returns true if field isReserve is set (has been assigned a value) and false otherwise */
  public boolean isSetIsReserve() {
    return EncodingUtils.testBit(__isset_bitfield, __ISRESERVE_ISSET_ID);
  }

  public void setIsReserveIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ISRESERVE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case CONF_ID:
      if (value == null) {
        unsetConfId();
      } else {
        setConfId((Integer)value);
      }
      break;

    case HOST_ID:
      if (value == null) {
        unsetHostId();
      } else {
        setHostId((Integer)value);
      }
      break;

    case CONF_PWD:
      if (value == null) {
        unsetConfPwd();
      } else {
        setConfPwd((String)value);
      }
      break;

    case IS_RESERVE:
      if (value == null) {
        unsetIsReserve();
      } else {
        setIsReserve((Byte)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case CONF_ID:
      return Integer.valueOf(getConfId());

    case HOST_ID:
      return Integer.valueOf(getHostId());

    case CONF_PWD:
      return getConfPwd();

    case IS_RESERVE:
      return Byte.valueOf(getIsReserve());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case CONF_ID:
      return isSetConfId();
    case HOST_ID:
      return isSetHostId();
    case CONF_PWD:
      return isSetConfPwd();
    case IS_RESERVE:
      return isSetIsReserve();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof InstantIQInviteContent)
      return this.equals((InstantIQInviteContent)that);
    return false;
  }

  public boolean equals(InstantIQInviteContent that) {
    if (that == null)
      return false;

    boolean this_present_confId = true;
    boolean that_present_confId = true;
    if (this_present_confId || that_present_confId) {
      if (!(this_present_confId && that_present_confId))
        return false;
      if (this.confId != that.confId)
        return false;
    }

    boolean this_present_hostId = true;
    boolean that_present_hostId = true;
    if (this_present_hostId || that_present_hostId) {
      if (!(this_present_hostId && that_present_hostId))
        return false;
      if (this.hostId != that.hostId)
        return false;
    }

    boolean this_present_confPwd = true && this.isSetConfPwd();
    boolean that_present_confPwd = true && that.isSetConfPwd();
    if (this_present_confPwd || that_present_confPwd) {
      if (!(this_present_confPwd && that_present_confPwd))
        return false;
      if (!this.confPwd.equals(that.confPwd))
        return false;
    }

    boolean this_present_isReserve = true && this.isSetIsReserve();
    boolean that_present_isReserve = true && that.isSetIsReserve();
    if (this_present_isReserve || that_present_isReserve) {
      if (!(this_present_isReserve && that_present_isReserve))
        return false;
      if (this.isReserve != that.isReserve)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_confId = true;
    list.add(present_confId);
    if (present_confId)
      list.add(confId);

    boolean present_hostId = true;
    list.add(present_hostId);
    if (present_hostId)
      list.add(hostId);

    boolean present_confPwd = true && (isSetConfPwd());
    list.add(present_confPwd);
    if (present_confPwd)
      list.add(confPwd);

    boolean present_isReserve = true && (isSetIsReserve());
    list.add(present_isReserve);
    if (present_isReserve)
      list.add(isReserve);

    return list.hashCode();
  }

  @Override
  public int compareTo(InstantIQInviteContent other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetConfId()).compareTo(other.isSetConfId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetConfId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.confId, other.confId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetHostId()).compareTo(other.isSetHostId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHostId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.hostId, other.hostId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetConfPwd()).compareTo(other.isSetConfPwd());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetConfPwd()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.confPwd, other.confPwd);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIsReserve()).compareTo(other.isSetIsReserve());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsReserve()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.isReserve, other.isReserve);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("InstantIQInviteContent(");
    boolean first = true;

    sb.append("confId:");
    sb.append(this.confId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("hostId:");
    sb.append(this.hostId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("confPwd:");
    if (this.confPwd == null) {
      sb.append("null");
    } else {
      sb.append(this.confPwd);
    }
    first = false;
    if (isSetIsReserve()) {
      if (!first) sb.append(", ");
      sb.append("isReserve:");
      sb.append(this.isReserve);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'confId' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'hostId' because it's a primitive and you chose the non-beans generator.
    if (confPwd == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'confPwd' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class InstantIQInviteContentStandardSchemeFactory implements SchemeFactory {
    public InstantIQInviteContentStandardScheme getScheme() {
      return new InstantIQInviteContentStandardScheme();
    }
  }

  private static class InstantIQInviteContentStandardScheme extends StandardScheme<InstantIQInviteContent> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, InstantIQInviteContent struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CONF_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.confId = iprot.readI32();
              struct.setConfIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // HOST_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.hostId = iprot.readI32();
              struct.setHostIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // CONF_PWD
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.confPwd = iprot.readString();
              struct.setConfPwdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // IS_RESERVE
            if (schemeField.type == org.apache.thrift.protocol.TType.BYTE) {
              struct.isReserve = iprot.readByte();
              struct.setIsReserveIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetConfId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'confId' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetHostId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'hostId' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, InstantIQInviteContent struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(CONF_ID_FIELD_DESC);
      oprot.writeI32(struct.confId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(HOST_ID_FIELD_DESC);
      oprot.writeI32(struct.hostId);
      oprot.writeFieldEnd();
      if (struct.confPwd != null) {
        oprot.writeFieldBegin(CONF_PWD_FIELD_DESC);
        oprot.writeString(struct.confPwd);
        oprot.writeFieldEnd();
      }
      if (struct.isSetIsReserve()) {
        oprot.writeFieldBegin(IS_RESERVE_FIELD_DESC);
        oprot.writeByte(struct.isReserve);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class InstantIQInviteContentTupleSchemeFactory implements SchemeFactory {
    public InstantIQInviteContentTupleScheme getScheme() {
      return new InstantIQInviteContentTupleScheme();
    }
  }

  private static class InstantIQInviteContentTupleScheme extends TupleScheme<InstantIQInviteContent> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, InstantIQInviteContent struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI32(struct.confId);
      oprot.writeI32(struct.hostId);
      oprot.writeString(struct.confPwd);
      BitSet optionals = new BitSet();
      if (struct.isSetIsReserve()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetIsReserve()) {
        oprot.writeByte(struct.isReserve);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, InstantIQInviteContent struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.confId = iprot.readI32();
      struct.setConfIdIsSet(true);
      struct.hostId = iprot.readI32();
      struct.setHostIdIsSet(true);
      struct.confPwd = iprot.readString();
      struct.setConfPwdIsSet(true);
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.isReserve = iprot.readByte();
        struct.setIsReserveIsSet(true);
      }
    }
  }

}

