/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.gnet.uc.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2016-8-12")
public class PositionUpdateContent implements org.apache.thrift.TBase<PositionUpdateContent, PositionUpdateContent._Fields>, java.io.Serializable, Cloneable, Comparable<PositionUpdateContent> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PositionUpdateContent");

  private static final org.apache.thrift.protocol.TField OPERATOR_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("operator_id", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField USER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("user_id", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField USER_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("user_name", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField NEW_POSITION_FIELD_DESC = new org.apache.thrift.protocol.TField("new_position", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField OLD_POSITION_FIELD_DESC = new org.apache.thrift.protocol.TField("old_position", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField DEPT_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("dept_name", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField DESC_FIELD_DESC = new org.apache.thrift.protocol.TField("desc", org.apache.thrift.protocol.TType.STRING, (short)7);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new PositionUpdateContentStandardSchemeFactory());
    schemes.put(TupleScheme.class, new PositionUpdateContentTupleSchemeFactory());
  }

  public int operator_id; // required
  public int user_id; // required
  public String user_name; // required
  public String new_position; // required
  public String old_position; // optional
  public String dept_name; // required
  public String desc; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    OPERATOR_ID((short)1, "operator_id"),
    USER_ID((short)2, "user_id"),
    USER_NAME((short)3, "user_name"),
    NEW_POSITION((short)4, "new_position"),
    OLD_POSITION((short)5, "old_position"),
    DEPT_NAME((short)6, "dept_name"),
    DESC((short)7, "desc");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // OPERATOR_ID
          return OPERATOR_ID;
        case 2: // USER_ID
          return USER_ID;
        case 3: // USER_NAME
          return USER_NAME;
        case 4: // NEW_POSITION
          return NEW_POSITION;
        case 5: // OLD_POSITION
          return OLD_POSITION;
        case 6: // DEPT_NAME
          return DEPT_NAME;
        case 7: // DESC
          return DESC;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __OPERATOR_ID_ISSET_ID = 0;
  private static final int __USER_ID_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.OLD_POSITION,_Fields.DESC};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.OPERATOR_ID, new org.apache.thrift.meta_data.FieldMetaData("operator_id", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.USER_ID, new org.apache.thrift.meta_data.FieldMetaData("user_id", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.USER_NAME, new org.apache.thrift.meta_data.FieldMetaData("user_name", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.NEW_POSITION, new org.apache.thrift.meta_data.FieldMetaData("new_position", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OLD_POSITION, new org.apache.thrift.meta_data.FieldMetaData("old_position", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DEPT_NAME, new org.apache.thrift.meta_data.FieldMetaData("dept_name", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DESC, new org.apache.thrift.meta_data.FieldMetaData("desc", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PositionUpdateContent.class, metaDataMap);
  }

  public PositionUpdateContent() {
  }

  public PositionUpdateContent(
    int operator_id,
    int user_id,
    String user_name,
    String new_position,
    String dept_name)
  {
    this();
    this.operator_id = operator_id;
    setOperator_idIsSet(true);
    this.user_id = user_id;
    setUser_idIsSet(true);
    this.user_name = user_name;
    this.new_position = new_position;
    this.dept_name = dept_name;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PositionUpdateContent(PositionUpdateContent other) {
    __isset_bitfield = other.__isset_bitfield;
    this.operator_id = other.operator_id;
    this.user_id = other.user_id;
    if (other.isSetUser_name()) {
      this.user_name = other.user_name;
    }
    if (other.isSetNew_position()) {
      this.new_position = other.new_position;
    }
    if (other.isSetOld_position()) {
      this.old_position = other.old_position;
    }
    if (other.isSetDept_name()) {
      this.dept_name = other.dept_name;
    }
    if (other.isSetDesc()) {
      this.desc = other.desc;
    }
  }

  public PositionUpdateContent deepCopy() {
    return new PositionUpdateContent(this);
  }

  @Override
  public void clear() {
    setOperator_idIsSet(false);
    this.operator_id = 0;
    setUser_idIsSet(false);
    this.user_id = 0;
    this.user_name = null;
    this.new_position = null;
    this.old_position = null;
    this.dept_name = null;
    this.desc = null;
  }

  public int getOperator_id() {
    return this.operator_id;
  }

  public PositionUpdateContent setOperator_id(int operator_id) {
    this.operator_id = operator_id;
    setOperator_idIsSet(true);
    return this;
  }

  public void unsetOperator_id() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __OPERATOR_ID_ISSET_ID);
  }

  /** Returns true if field operator_id is set (has been assigned a value) and false otherwise */
  public boolean isSetOperator_id() {
    return EncodingUtils.testBit(__isset_bitfield, __OPERATOR_ID_ISSET_ID);
  }

  public void setOperator_idIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __OPERATOR_ID_ISSET_ID, value);
  }

  public int getUser_id() {
    return this.user_id;
  }

  public PositionUpdateContent setUser_id(int user_id) {
    this.user_id = user_id;
    setUser_idIsSet(true);
    return this;
  }

  public void unsetUser_id() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __USER_ID_ISSET_ID);
  }

  /** Returns true if field user_id is set (has been assigned a value) and false otherwise */
  public boolean isSetUser_id() {
    return EncodingUtils.testBit(__isset_bitfield, __USER_ID_ISSET_ID);
  }

  public void setUser_idIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __USER_ID_ISSET_ID, value);
  }

  public String getUser_name() {
    return this.user_name;
  }

  public PositionUpdateContent setUser_name(String user_name) {
    this.user_name = user_name;
    return this;
  }

  public void unsetUser_name() {
    this.user_name = null;
  }

  /** Returns true if field user_name is set (has been assigned a value) and false otherwise */
  public boolean isSetUser_name() {
    return this.user_name != null;
  }

  public void setUser_nameIsSet(boolean value) {
    if (!value) {
      this.user_name = null;
    }
  }

  public String getNew_position() {
    return this.new_position;
  }

  public PositionUpdateContent setNew_position(String new_position) {
    this.new_position = new_position;
    return this;
  }

  public void unsetNew_position() {
    this.new_position = null;
  }

  /** Returns true if field new_position is set (has been assigned a value) and false otherwise */
  public boolean isSetNew_position() {
    return this.new_position != null;
  }

  public void setNew_positionIsSet(boolean value) {
    if (!value) {
      this.new_position = null;
    }
  }

  public String getOld_position() {
    return this.old_position;
  }

  public PositionUpdateContent setOld_position(String old_position) {
    this.old_position = old_position;
    return this;
  }

  public void unsetOld_position() {
    this.old_position = null;
  }

  /** Returns true if field old_position is set (has been assigned a value) and false otherwise */
  public boolean isSetOld_position() {
    return this.old_position != null;
  }

  public void setOld_positionIsSet(boolean value) {
    if (!value) {
      this.old_position = null;
    }
  }

  public String getDept_name() {
    return this.dept_name;
  }

  public PositionUpdateContent setDept_name(String dept_name) {
    this.dept_name = dept_name;
    return this;
  }

  public void unsetDept_name() {
    this.dept_name = null;
  }

  /** Returns true if field dept_name is set (has been assigned a value) and false otherwise */
  public boolean isSetDept_name() {
    return this.dept_name != null;
  }

  public void setDept_nameIsSet(boolean value) {
    if (!value) {
      this.dept_name = null;
    }
  }

  public String getDesc() {
    return this.desc;
  }

  public PositionUpdateContent setDesc(String desc) {
    this.desc = desc;
    return this;
  }

  public void unsetDesc() {
    this.desc = null;
  }

  /** Returns true if field desc is set (has been assigned a value) and false otherwise */
  public boolean isSetDesc() {
    return this.desc != null;
  }

  public void setDescIsSet(boolean value) {
    if (!value) {
      this.desc = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case OPERATOR_ID:
      if (value == null) {
        unsetOperator_id();
      } else {
        setOperator_id((Integer)value);
      }
      break;

    case USER_ID:
      if (value == null) {
        unsetUser_id();
      } else {
        setUser_id((Integer)value);
      }
      break;

    case USER_NAME:
      if (value == null) {
        unsetUser_name();
      } else {
        setUser_name((String)value);
      }
      break;

    case NEW_POSITION:
      if (value == null) {
        unsetNew_position();
      } else {
        setNew_position((String)value);
      }
      break;

    case OLD_POSITION:
      if (value == null) {
        unsetOld_position();
      } else {
        setOld_position((String)value);
      }
      break;

    case DEPT_NAME:
      if (value == null) {
        unsetDept_name();
      } else {
        setDept_name((String)value);
      }
      break;

    case DESC:
      if (value == null) {
        unsetDesc();
      } else {
        setDesc((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case OPERATOR_ID:
      return Integer.valueOf(getOperator_id());

    case USER_ID:
      return Integer.valueOf(getUser_id());

    case USER_NAME:
      return getUser_name();

    case NEW_POSITION:
      return getNew_position();

    case OLD_POSITION:
      return getOld_position();

    case DEPT_NAME:
      return getDept_name();

    case DESC:
      return getDesc();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case OPERATOR_ID:
      return isSetOperator_id();
    case USER_ID:
      return isSetUser_id();
    case USER_NAME:
      return isSetUser_name();
    case NEW_POSITION:
      return isSetNew_position();
    case OLD_POSITION:
      return isSetOld_position();
    case DEPT_NAME:
      return isSetDept_name();
    case DESC:
      return isSetDesc();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof PositionUpdateContent)
      return this.equals((PositionUpdateContent)that);
    return false;
  }

  public boolean equals(PositionUpdateContent that) {
    if (that == null)
      return false;

    boolean this_present_operator_id = true;
    boolean that_present_operator_id = true;
    if (this_present_operator_id || that_present_operator_id) {
      if (!(this_present_operator_id && that_present_operator_id))
        return false;
      if (this.operator_id != that.operator_id)
        return false;
    }

    boolean this_present_user_id = true;
    boolean that_present_user_id = true;
    if (this_present_user_id || that_present_user_id) {
      if (!(this_present_user_id && that_present_user_id))
        return false;
      if (this.user_id != that.user_id)
        return false;
    }

    boolean this_present_user_name = true && this.isSetUser_name();
    boolean that_present_user_name = true && that.isSetUser_name();
    if (this_present_user_name || that_present_user_name) {
      if (!(this_present_user_name && that_present_user_name))
        return false;
      if (!this.user_name.equals(that.user_name))
        return false;
    }

    boolean this_present_new_position = true && this.isSetNew_position();
    boolean that_present_new_position = true && that.isSetNew_position();
    if (this_present_new_position || that_present_new_position) {
      if (!(this_present_new_position && that_present_new_position))
        return false;
      if (!this.new_position.equals(that.new_position))
        return false;
    }

    boolean this_present_old_position = true && this.isSetOld_position();
    boolean that_present_old_position = true && that.isSetOld_position();
    if (this_present_old_position || that_present_old_position) {
      if (!(this_present_old_position && that_present_old_position))
        return false;
      if (!this.old_position.equals(that.old_position))
        return false;
    }

    boolean this_present_dept_name = true && this.isSetDept_name();
    boolean that_present_dept_name = true && that.isSetDept_name();
    if (this_present_dept_name || that_present_dept_name) {
      if (!(this_present_dept_name && that_present_dept_name))
        return false;
      if (!this.dept_name.equals(that.dept_name))
        return false;
    }

    boolean this_present_desc = true && this.isSetDesc();
    boolean that_present_desc = true && that.isSetDesc();
    if (this_present_desc || that_present_desc) {
      if (!(this_present_desc && that_present_desc))
        return false;
      if (!this.desc.equals(that.desc))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_operator_id = true;
    list.add(present_operator_id);
    if (present_operator_id)
      list.add(operator_id);

    boolean present_user_id = true;
    list.add(present_user_id);
    if (present_user_id)
      list.add(user_id);

    boolean present_user_name = true && (isSetUser_name());
    list.add(present_user_name);
    if (present_user_name)
      list.add(user_name);

    boolean present_new_position = true && (isSetNew_position());
    list.add(present_new_position);
    if (present_new_position)
      list.add(new_position);

    boolean present_old_position = true && (isSetOld_position());
    list.add(present_old_position);
    if (present_old_position)
      list.add(old_position);

    boolean present_dept_name = true && (isSetDept_name());
    list.add(present_dept_name);
    if (present_dept_name)
      list.add(dept_name);

    boolean present_desc = true && (isSetDesc());
    list.add(present_desc);
    if (present_desc)
      list.add(desc);

    return list.hashCode();
  }

  @Override
  public int compareTo(PositionUpdateContent other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetOperator_id()).compareTo(other.isSetOperator_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOperator_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.operator_id, other.operator_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUser_id()).compareTo(other.isSetUser_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUser_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.user_id, other.user_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUser_name()).compareTo(other.isSetUser_name());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUser_name()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.user_name, other.user_name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNew_position()).compareTo(other.isSetNew_position());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNew_position()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.new_position, other.new_position);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOld_position()).compareTo(other.isSetOld_position());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOld_position()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.old_position, other.old_position);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDept_name()).compareTo(other.isSetDept_name());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDept_name()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dept_name, other.dept_name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDesc()).compareTo(other.isSetDesc());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDesc()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.desc, other.desc);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("PositionUpdateContent(");
    boolean first = true;

    sb.append("operator_id:");
    sb.append(this.operator_id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("user_id:");
    sb.append(this.user_id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("user_name:");
    if (this.user_name == null) {
      sb.append("null");
    } else {
      sb.append(this.user_name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("new_position:");
    if (this.new_position == null) {
      sb.append("null");
    } else {
      sb.append(this.new_position);
    }
    first = false;
    if (isSetOld_position()) {
      if (!first) sb.append(", ");
      sb.append("old_position:");
      if (this.old_position == null) {
        sb.append("null");
      } else {
        sb.append(this.old_position);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("dept_name:");
    if (this.dept_name == null) {
      sb.append("null");
    } else {
      sb.append(this.dept_name);
    }
    first = false;
    if (isSetDesc()) {
      if (!first) sb.append(", ");
      sb.append("desc:");
      if (this.desc == null) {
        sb.append("null");
      } else {
        sb.append(this.desc);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'operator_id' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'user_id' because it's a primitive and you chose the non-beans generator.
    if (user_name == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'user_name' was not present! Struct: " + toString());
    }
    if (new_position == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'new_position' was not present! Struct: " + toString());
    }
    if (dept_name == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'dept_name' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PositionUpdateContentStandardSchemeFactory implements SchemeFactory {
    public PositionUpdateContentStandardScheme getScheme() {
      return new PositionUpdateContentStandardScheme();
    }
  }

  private static class PositionUpdateContentStandardScheme extends StandardScheme<PositionUpdateContent> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, PositionUpdateContent struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // OPERATOR_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.operator_id = iprot.readI32();
              struct.setOperator_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // USER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.user_id = iprot.readI32();
              struct.setUser_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // USER_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.user_name = iprot.readString();
              struct.setUser_nameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // NEW_POSITION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.new_position = iprot.readString();
              struct.setNew_positionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // OLD_POSITION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.old_position = iprot.readString();
              struct.setOld_positionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // DEPT_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.dept_name = iprot.readString();
              struct.setDept_nameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // DESC
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.desc = iprot.readString();
              struct.setDescIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetOperator_id()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'operator_id' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetUser_id()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'user_id' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, PositionUpdateContent struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(OPERATOR_ID_FIELD_DESC);
      oprot.writeI32(struct.operator_id);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(USER_ID_FIELD_DESC);
      oprot.writeI32(struct.user_id);
      oprot.writeFieldEnd();
      if (struct.user_name != null) {
        oprot.writeFieldBegin(USER_NAME_FIELD_DESC);
        oprot.writeString(struct.user_name);
        oprot.writeFieldEnd();
      }
      if (struct.new_position != null) {
        oprot.writeFieldBegin(NEW_POSITION_FIELD_DESC);
        oprot.writeString(struct.new_position);
        oprot.writeFieldEnd();
      }
      if (struct.old_position != null) {
        if (struct.isSetOld_position()) {
          oprot.writeFieldBegin(OLD_POSITION_FIELD_DESC);
          oprot.writeString(struct.old_position);
          oprot.writeFieldEnd();
        }
      }
      if (struct.dept_name != null) {
        oprot.writeFieldBegin(DEPT_NAME_FIELD_DESC);
        oprot.writeString(struct.dept_name);
        oprot.writeFieldEnd();
      }
      if (struct.desc != null) {
        if (struct.isSetDesc()) {
          oprot.writeFieldBegin(DESC_FIELD_DESC);
          oprot.writeString(struct.desc);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PositionUpdateContentTupleSchemeFactory implements SchemeFactory {
    public PositionUpdateContentTupleScheme getScheme() {
      return new PositionUpdateContentTupleScheme();
    }
  }

  private static class PositionUpdateContentTupleScheme extends TupleScheme<PositionUpdateContent> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PositionUpdateContent struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI32(struct.operator_id);
      oprot.writeI32(struct.user_id);
      oprot.writeString(struct.user_name);
      oprot.writeString(struct.new_position);
      oprot.writeString(struct.dept_name);
      BitSet optionals = new BitSet();
      if (struct.isSetOld_position()) {
        optionals.set(0);
      }
      if (struct.isSetDesc()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetOld_position()) {
        oprot.writeString(struct.old_position);
      }
      if (struct.isSetDesc()) {
        oprot.writeString(struct.desc);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PositionUpdateContent struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.operator_id = iprot.readI32();
      struct.setOperator_idIsSet(true);
      struct.user_id = iprot.readI32();
      struct.setUser_idIsSet(true);
      struct.user_name = iprot.readString();
      struct.setUser_nameIsSet(true);
      struct.new_position = iprot.readString();
      struct.setNew_positionIsSet(true);
      struct.dept_name = iprot.readString();
      struct.setDept_nameIsSet(true);
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.old_position = iprot.readString();
        struct.setOld_positionIsSet(true);
      }
      if (incoming.get(1)) {
        struct.desc = iprot.readString();
        struct.setDescIsSet(true);
      }
    }
  }

}

