/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.gnet.uc.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum RemoteAssistanceMessageId implements org.apache.thrift.TEnum {
  RemoteAssistanceInvite(1),
  RemoteAssistanceAccept(2),
  RemoteAssistanceReject(3),
  RemoteAssistanceEnd(4),
  RemoteAssistanceCancel(5);

  private final int value;

  private RemoteAssistanceMessageId(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static RemoteAssistanceMessageId findByValue(int value) { 
    switch (value) {
      case 1:
        return RemoteAssistanceInvite;
      case 2:
        return RemoteAssistanceAccept;
      case 3:
        return RemoteAssistanceReject;
      case 4:
        return RemoteAssistanceEnd;
      case 5:
        return RemoteAssistanceCancel;
      default:
        return null;
    }
  }
}
