/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.gnet.uc.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum SyncMessageId implements org.apache.thrift.TEnum {
  SessionTopSet(1),
  SessionTopUnset(2),
  AtMessageReaded(16),
  UserLoginNotify(32),
  GroupScopeNotify(48),
  ContactsRelationNotify(64),
  MeetingAlertSettingNotify(80);

  private final int value;

  private SyncMessageId(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static SyncMessageId findByValue(int value) { 
    switch (value) {
      case 1:
        return SessionTopSet;
      case 2:
        return SessionTopUnset;
      case 16:
        return AtMessageReaded;
      case 32:
        return UserLoginNotify;
      case 48:
        return GroupScopeNotify;
      case 64:
        return ContactsRelationNotify;
      case 80:
        return MeetingAlertSettingNotify;
      default:
        return null;
    }
  }
}
