/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.gnet.uc.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum SyncMessageType implements org.apache.thrift.TEnum {
  SessionTopType(1),
  AtMessageType(2),
  UserLoginType(3),
  GroupScopeType(4),
  ContactsRelationType(5),
  UserSettingType(6);

  private final int value;

  private SyncMessageType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static SyncMessageType findByValue(int value) { 
    switch (value) {
      case 1:
        return SessionTopType;
      case 2:
        return AtMessageType;
      case 3:
        return UserLoginType;
      case 4:
        return GroupScopeType;
      case 5:
        return ContactsRelationType;
      case 6:
        return UserSettingType;
      default:
        return null;
    }
  }
}
