/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.gnet.uc.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2016-8-12")
public class SystemWelcomeContent implements org.apache.thrift.TBase<SystemWelcomeContent, SystemWelcomeContent._Fields>, java.io.Serializable, Cloneable, Comparable<SystemWelcomeContent> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SystemWelcomeContent");

  private static final org.apache.thrift.protocol.TField TITLE_FIELD_DESC = new org.apache.thrift.protocol.TField("title", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField IMAGE_URL_FIELD_DESC = new org.apache.thrift.protocol.TField("image_url", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField DESC_FIELD_DESC = new org.apache.thrift.protocol.TField("desc", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField TARGET_LINK_FIELD_DESC = new org.apache.thrift.protocol.TField("target_link", org.apache.thrift.protocol.TType.STRING, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SystemWelcomeContentStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SystemWelcomeContentTupleSchemeFactory());
  }

  public String title; // required
  public String image_url; // required
  public String desc; // optional
  public String target_link; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TITLE((short)1, "title"),
    IMAGE_URL((short)2, "image_url"),
    DESC((short)3, "desc"),
    TARGET_LINK((short)4, "target_link");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TITLE
          return TITLE;
        case 2: // IMAGE_URL
          return IMAGE_URL;
        case 3: // DESC
          return DESC;
        case 4: // TARGET_LINK
          return TARGET_LINK;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.DESC,_Fields.TARGET_LINK};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TITLE, new org.apache.thrift.meta_data.FieldMetaData("title", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.IMAGE_URL, new org.apache.thrift.meta_data.FieldMetaData("image_url", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DESC, new org.apache.thrift.meta_data.FieldMetaData("desc", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TARGET_LINK, new org.apache.thrift.meta_data.FieldMetaData("target_link", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SystemWelcomeContent.class, metaDataMap);
  }

  public SystemWelcomeContent() {
  }

  public SystemWelcomeContent(
    String title,
    String image_url)
  {
    this();
    this.title = title;
    this.image_url = image_url;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SystemWelcomeContent(SystemWelcomeContent other) {
    if (other.isSetTitle()) {
      this.title = other.title;
    }
    if (other.isSetImage_url()) {
      this.image_url = other.image_url;
    }
    if (other.isSetDesc()) {
      this.desc = other.desc;
    }
    if (other.isSetTarget_link()) {
      this.target_link = other.target_link;
    }
  }

  public SystemWelcomeContent deepCopy() {
    return new SystemWelcomeContent(this);
  }

  @Override
  public void clear() {
    this.title = null;
    this.image_url = null;
    this.desc = null;
    this.target_link = null;
  }

  public String getTitle() {
    return this.title;
  }

  public SystemWelcomeContent setTitle(String title) {
    this.title = title;
    return this;
  }

  public void unsetTitle() {
    this.title = null;
  }

  /** Returns true if field title is set (has been assigned a value) and false otherwise */
  public boolean isSetTitle() {
    return this.title != null;
  }

  public void setTitleIsSet(boolean value) {
    if (!value) {
      this.title = null;
    }
  }

  public String getImage_url() {
    return this.image_url;
  }

  public SystemWelcomeContent setImage_url(String image_url) {
    this.image_url = image_url;
    return this;
  }

  public void unsetImage_url() {
    this.image_url = null;
  }

  /** Returns true if field image_url is set (has been assigned a value) and false otherwise */
  public boolean isSetImage_url() {
    return this.image_url != null;
  }

  public void setImage_urlIsSet(boolean value) {
    if (!value) {
      this.image_url = null;
    }
  }

  public String getDesc() {
    return this.desc;
  }

  public SystemWelcomeContent setDesc(String desc) {
    this.desc = desc;
    return this;
  }

  public void unsetDesc() {
    this.desc = null;
  }

  /** Returns true if field desc is set (has been assigned a value) and false otherwise */
  public boolean isSetDesc() {
    return this.desc != null;
  }

  public void setDescIsSet(boolean value) {
    if (!value) {
      this.desc = null;
    }
  }

  public String getTarget_link() {
    return this.target_link;
  }

  public SystemWelcomeContent setTarget_link(String target_link) {
    this.target_link = target_link;
    return this;
  }

  public void unsetTarget_link() {
    this.target_link = null;
  }

  /** Returns true if field target_link is set (has been assigned a value) and false otherwise */
  public boolean isSetTarget_link() {
    return this.target_link != null;
  }

  public void setTarget_linkIsSet(boolean value) {
    if (!value) {
      this.target_link = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TITLE:
      if (value == null) {
        unsetTitle();
      } else {
        setTitle((String)value);
      }
      break;

    case IMAGE_URL:
      if (value == null) {
        unsetImage_url();
      } else {
        setImage_url((String)value);
      }
      break;

    case DESC:
      if (value == null) {
        unsetDesc();
      } else {
        setDesc((String)value);
      }
      break;

    case TARGET_LINK:
      if (value == null) {
        unsetTarget_link();
      } else {
        setTarget_link((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TITLE:
      return getTitle();

    case IMAGE_URL:
      return getImage_url();

    case DESC:
      return getDesc();

    case TARGET_LINK:
      return getTarget_link();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TITLE:
      return isSetTitle();
    case IMAGE_URL:
      return isSetImage_url();
    case DESC:
      return isSetDesc();
    case TARGET_LINK:
      return isSetTarget_link();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SystemWelcomeContent)
      return this.equals((SystemWelcomeContent)that);
    return false;
  }

  public boolean equals(SystemWelcomeContent that) {
    if (that == null)
      return false;

    boolean this_present_title = true && this.isSetTitle();
    boolean that_present_title = true && that.isSetTitle();
    if (this_present_title || that_present_title) {
      if (!(this_present_title && that_present_title))
        return false;
      if (!this.title.equals(that.title))
        return false;
    }

    boolean this_present_image_url = true && this.isSetImage_url();
    boolean that_present_image_url = true && that.isSetImage_url();
    if (this_present_image_url || that_present_image_url) {
      if (!(this_present_image_url && that_present_image_url))
        return false;
      if (!this.image_url.equals(that.image_url))
        return false;
    }

    boolean this_present_desc = true && this.isSetDesc();
    boolean that_present_desc = true && that.isSetDesc();
    if (this_present_desc || that_present_desc) {
      if (!(this_present_desc && that_present_desc))
        return false;
      if (!this.desc.equals(that.desc))
        return false;
    }

    boolean this_present_target_link = true && this.isSetTarget_link();
    boolean that_present_target_link = true && that.isSetTarget_link();
    if (this_present_target_link || that_present_target_link) {
      if (!(this_present_target_link && that_present_target_link))
        return false;
      if (!this.target_link.equals(that.target_link))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_title = true && (isSetTitle());
    list.add(present_title);
    if (present_title)
      list.add(title);

    boolean present_image_url = true && (isSetImage_url());
    list.add(present_image_url);
    if (present_image_url)
      list.add(image_url);

    boolean present_desc = true && (isSetDesc());
    list.add(present_desc);
    if (present_desc)
      list.add(desc);

    boolean present_target_link = true && (isSetTarget_link());
    list.add(present_target_link);
    if (present_target_link)
      list.add(target_link);

    return list.hashCode();
  }

  @Override
  public int compareTo(SystemWelcomeContent other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetTitle()).compareTo(other.isSetTitle());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTitle()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.title, other.title);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetImage_url()).compareTo(other.isSetImage_url());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImage_url()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.image_url, other.image_url);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDesc()).compareTo(other.isSetDesc());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDesc()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.desc, other.desc);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTarget_link()).compareTo(other.isSetTarget_link());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTarget_link()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.target_link, other.target_link);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SystemWelcomeContent(");
    boolean first = true;

    sb.append("title:");
    if (this.title == null) {
      sb.append("null");
    } else {
      sb.append(this.title);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("image_url:");
    if (this.image_url == null) {
      sb.append("null");
    } else {
      sb.append(this.image_url);
    }
    first = false;
    if (isSetDesc()) {
      if (!first) sb.append(", ");
      sb.append("desc:");
      if (this.desc == null) {
        sb.append("null");
      } else {
        sb.append(this.desc);
      }
      first = false;
    }
    if (isSetTarget_link()) {
      if (!first) sb.append(", ");
      sb.append("target_link:");
      if (this.target_link == null) {
        sb.append("null");
      } else {
        sb.append(this.target_link);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (title == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'title' was not present! Struct: " + toString());
    }
    if (image_url == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'image_url' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SystemWelcomeContentStandardSchemeFactory implements SchemeFactory {
    public SystemWelcomeContentStandardScheme getScheme() {
      return new SystemWelcomeContentStandardScheme();
    }
  }

  private static class SystemWelcomeContentStandardScheme extends StandardScheme<SystemWelcomeContent> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SystemWelcomeContent struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TITLE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.title = iprot.readString();
              struct.setTitleIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // IMAGE_URL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.image_url = iprot.readString();
              struct.setImage_urlIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // DESC
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.desc = iprot.readString();
              struct.setDescIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // TARGET_LINK
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.target_link = iprot.readString();
              struct.setTarget_linkIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SystemWelcomeContent struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.title != null) {
        oprot.writeFieldBegin(TITLE_FIELD_DESC);
        oprot.writeString(struct.title);
        oprot.writeFieldEnd();
      }
      if (struct.image_url != null) {
        oprot.writeFieldBegin(IMAGE_URL_FIELD_DESC);
        oprot.writeString(struct.image_url);
        oprot.writeFieldEnd();
      }
      if (struct.desc != null) {
        if (struct.isSetDesc()) {
          oprot.writeFieldBegin(DESC_FIELD_DESC);
          oprot.writeString(struct.desc);
          oprot.writeFieldEnd();
        }
      }
      if (struct.target_link != null) {
        if (struct.isSetTarget_link()) {
          oprot.writeFieldBegin(TARGET_LINK_FIELD_DESC);
          oprot.writeString(struct.target_link);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SystemWelcomeContentTupleSchemeFactory implements SchemeFactory {
    public SystemWelcomeContentTupleScheme getScheme() {
      return new SystemWelcomeContentTupleScheme();
    }
  }

  private static class SystemWelcomeContentTupleScheme extends TupleScheme<SystemWelcomeContent> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SystemWelcomeContent struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.title);
      oprot.writeString(struct.image_url);
      BitSet optionals = new BitSet();
      if (struct.isSetDesc()) {
        optionals.set(0);
      }
      if (struct.isSetTarget_link()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetDesc()) {
        oprot.writeString(struct.desc);
      }
      if (struct.isSetTarget_link()) {
        oprot.writeString(struct.target_link);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SystemWelcomeContent struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.title = iprot.readString();
      struct.setTitleIsSet(true);
      struct.image_url = iprot.readString();
      struct.setImage_urlIsSet(true);
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.desc = iprot.readString();
        struct.setDescIsSet(true);
      }
      if (incoming.get(1)) {
        struct.target_link = iprot.readString();
        struct.setTarget_linkIsSet(true);
      }
    }
  }

}

